<header id="header">
    <div id="hd_wrap">
        <h1 id="logo"><i class="fa fa-address-card fa-3x" aria-hidden="true"></i><span>시스템</span></a></h1>
        <ul class="menu">
            <li><a href="/spotMng/spotInfoList.php">현장관리</a></li>
            <li><a href="/actPlan/monthlyPlan.php">활동계획</a></li>
            <li><a href="/check/unreasonableStatusList.php">점검</a></li>
            <li><a href="/etm/safeHealthEduList.php">교육/훈련/회의</a></li>
            <li><a href="/safeAct/riskEvaluationList.php">안전활동</a></li>
            <li><a href="/healthAct/chemicalIOList.php">보건활동</a></li>
            <li><a href="/bbs/noticeList.php">게시판</a></li>
            <li><a href="/system/userMngList.php">시스템관리</a></li>
            <nav class="sub_menu2">
                <section>
                    <dl>
                        <dd><a href="/spotMng/spotInfoList.php">현장정보</a></dd>
                        <dd><a href="/spotMng/spotEstblDspthList.php">현장개설통보서</a></dd>
                        <%-- <dd><a href="sub00103.php">조립장개설통보서</a></dd> --%>
                        <dd><a href="/spotMng/assignmentStatusList.php">선임현황</a></dd>
                        <dd><a href="/spotMng/orgChart.php">조직도 및 비상연락망</a></dd>
                        <dd><a href="/spotMng/coorpMngList.php">협력사관리</a></dd>
                        <dd><a href="/spotMng/laborerMngList.php">근로자관리</a></dd>
                        <dd><a href="/spotMng/eqpmnMngList.php">장비관리</a></dd>
                        <%-- <dd><a href="sub00109.php">관리자메뉴</a></dd> --%>
                    </dl>
                    <dl>
                        <dd><a href="/actPlan/monthlyPlan.php">월간관리계획</a></dd>
                        <dd><a href="/actPlan/wOpertPlanList.php">작업계획서</a></dd>
                        <dd><a href="/actPlan/safeHealthRegisterList.php">안전보건대장</a></dd>
                        <dd><a href="/actPlan/riskPreventionPlanList.php">유해위험방지계획서</a></dd>
                        <dd><a href="/actPlan/safeMngPlanList.php">안전관리계획</a></dd>
                        <!-- 			<dd><a href="sub00206.php">점검일정</a></dd> -->
                        <!-- 			<dd><a href="sub00207.php">연간관리계획</a></dd> -->
                    </dl>
                    <dl>
                        <dd><a href="/check/unreasonableStatusList.php">안전보건불합리현황</a></dd>
                        <dd><a href="/check/safeHealthCheckList.php">합동안전보건점검</a></dd>
                        <!-- 			<dd><a href="sub00303.php">점검실적</a></dd> -->
                        <dd><a href="/check/circuitCheckList.php">순회점검</a></dd>
                        <dd><a href="/check/themeCheck.php">테마점검</a></dd>
                        <dd><a href="/check/hedofcCheckList.php">본사점검</a></dd>
                        <dd><a href="/check/extrlCheckList.php">외부점검</a></dd>
                        <dd><a href="/check/dsstrPrevntCchList.php">재해예방기술지도</a></dd>
                    </dl>
                    <dl>
                        <dd><a href="/etm/safeHealthEduList.php">안전보건교육</a></dd>
                        <dd><a href="/etm/safeHealthCouncil.php">안전보건협의체</a></dd>
                        <dd><a href="/etm/jLaborMngConference.php">노사협의체</a></dd>
                        <dd><a href="/etm/industSafeHealthCommitteeList.php">산업안전보건위원회</a></dd>
                        <dd><a href="/etm/emgncManagtCntrmsrList.php">비상조치대응</a></dd>
                        <dd><a href="/etm/fyrEdcPlanList.php">연간안전보건교육계획</a></dd>
                    </dl>
                    <dl>
                        <dd><a href="/safeAct/riskEvaluationList.php">위험성평가</a></dd>
                        <dd><a href="/safeAct/safeActDiaryList.php">안전활동일지</a></dd>
                        <dd><a href="/safeAct/TBMList.php">TBM안전일지</a></dd>
                        <!-- 			<dd><a href="/safeAct/riskEvaluationList.php">위험작업허가신청</a></dd> -->
                        <dd><a href="/safeAct/safeHealthManagectList.php">안전보건관리비</a></dd>
                        <dd><a href="/safeAct/hrmflnsMchnMngList.php">유해위험기계기구관리</a></dd>
                        <dd><a href="/safeAct/labrumSafeMngList.php">연구실안전관리</a></dd>
                    </dl>
                    <dl>
                        <dd><a href="/healthAct/chemicalIOList.php">화학물질반입</a></dd>
                        <dd><a href="/healthAct/healthDiagnosisList.php">건강진단</a></dd>
                        <dd><a href="/healthAct/opertEnvrnMesureList.php">작업환경측정</a></dd>
                        <dd><a href="/healthAct/mctmdList.php">근골격계질환</a></dd>
                        <dd><a href="/healthAct/healthIncrzList.php">건강증진</a></dd>
                    </dl>
                    <dl>
                        <dd><a href="/bbs/noticeList.php">공지사항</a></dd>
                        <dd><a href="/bbs/recsroomList.php">자료실</a></dd>
                        <dd><a href="/bbs/manualList.php">매뉴얼</a></dd>
                        <dd><a href="/bbs/stdOpertProcssList.php">표준작업절차</a></dd>
                        <dd><a href="/bbs/dsstrCaseList.php">재해사례</a></dd>
                        <dd><a href="sub00706.php">안전용품업체</a></dd>
                        <dd><a href="/bbs/vocList.php">VOC</a></dd>
                    </dl>
                    <dl>
                        <dd><a href="/system/userMngList.php">사용자관리</a></dd>
                        <dd><a href="/system/connectLogList.php">접속로그</a></dd>
                        <dd><a href="sub00803.php">시스템 사용관리</a></dd>
                        <dd><a href="/system/codeMngList.php">코드관리</a></dd>
                        <dd><a href="/system/authMngList.php">권한관리</a></dd>
                        <dd><a href="/system/popupMngList.php">팝업관리</a></dd>
                        <dd><a href="/system/accessAuth.php">접근권한</a></dd>
                        <dd><a href="/system/categoryList.php">카테고리관리</a></dd>
                    </dl>
                </section>
            </nav>
        </ul>
        <dl class="tnb">
            <dd class="hd_icon">
                <a class="tablet"><i class="fas fa-bars"></i></a>
                <a href="/loginView.php"><i class="fas fa-user"></i></a>
            </dd>
        </dl>
    </div>
</header>
<nav class="sub_menu">
	<section>
		<dl>
			<dd><a href="/spotMng/spotInfoList.php">현장정보</a></dd>
			<dd><a href="sub00102.php">현장개설통보서</a></dd>
			<%-- <dd><a href="sub00103.php">조립장개설통보서</a></dd> --%>
			<dd><a href="sub00104.php">선임현황</a></dd>
			<dd><a href="/spotMng/orgChart.php">조직도 및 비상연락망</a></dd>
			<dd><a href="/spotMng/coorpMngList.php">협력사관리</a></dd>
<!-- 			<dd><a href="sub00107.php">근로자관리</a></dd> -->
			<dd><a href="eqpmnMngList.php">장비관리</a></dd>
			<%-- <dd><a href="sub00109.php">관리자메뉴</a></dd> --%>
		</dl>
		<dl>
			<dd><a href="/actPlan/monthlyPlan.php">월간관리계획</a></dd>
			<dd><a href="/actPlan/wOpertPlanList.php">작업계획서</a></dd>
			<dd><a href="/actPlan/safeHealthRegisterList.php">안전보건대장</a></dd>
			<dd><a href="/actPlan/riskPreventionPlanList.php">유해위험방지계획서</a></dd>
			<dd><a href="/actPlan/safeMngPlanList.php">안전관리계획</a></dd>
<!-- 			<dd><a href="sub00206.php">점검일정</a></dd> -->
<!-- 			<dd><a href="sub00207.php">연간관리계획</a></dd> -->
		</dl>
		<dl>
			<dd><a href="/check/unreasonableStatusList.php">안전보건불합리현황</a></dd>
			<dd><a href="/check/safeHealthCheckList.php">합동안전보건점검</a></dd>
<!-- 			<dd><a href="sub00303.php">점검실적</a></dd> -->
			<dd><a href="/check/circuitCheckList.php">순회점검</a></dd>
			<dd><a href="/check/themeCheck.php">테마점검</a></dd>
			<dd><a href="/check/hedofcCheckList.php">본사점검</a></dd>
			<dd><a href="/check/extrlCheckList.php">외부점검</a></dd>
			<dd><a href="/check/dsstrPrevntCchList.php">재해예방기술지도</a></dd>
		</dl>
		 <dl>
		 	<dd><a href="/etm/safeHealthEduList.php">안전보건교육</a></dd>
			<dd><a href="/etm/safeHealthCouncil.php">안전보건협의체</a></dd>
		 	<dd><a href="/etm/jLaborMngConference.php">노사협의체</a></dd>
			<dd><a href="/etm/industSafeHealthCommitteeList.php">산업안전보건위원회</a></dd>
			<dd><a href="/etm/emgncManagtCntrmsrList.php">비상조치대응</a></dd>
			<dd><a href="/etm/fyrEdcPlanList.php.php">연간안전보건교육계획</a></dd>
		</dl>
		 <dl>
		 	<dd><a href="/safeAct/riskEvaluationList.php">위험성평가</a></dd>
			<dd><a href="/safeAct/safeActDiaryList.php">안전활동일지</a></dd>
			<dd><a href="/safeAct/TBMList.php">TBM안전일지</a></dd>
<!-- 			<dd><a href="sub00504.php">위험작업허가신청</a></dd> -->
			<dd><a href="/safeAct/safeHealthManagectList.php">안전보건관리비</a></dd>
			<dd><a href="/safeAct/hrmflnsMchnMngList.php">유해위험기계기구관리</a></dd>
			<dd><a href="/safeAct/labrumSafeMngList.php">연구실안전관리</a></dd>
		 </dl>  
		<dl>
			<dd><a href="/healthAct/chemicalIOList.php">화학물질반입</a></dd>
			<dd><a href="/healthAct/healthDiagnosisList.php">건강진단</a></dd>
			<dd><a href="/healthAct/opertEnvrnMesureList.php">작업환경측정</a></dd>
			<dd><a href="/healthAct/mctmdList.php">근골격계질환</a></dd>
			<dd><a href="/healthAct/healthIncrzList.php">건강증진</a></dd>
		</dl>
		<dl>
			<dd><a href="/bbs/noticeList.php">공지사항</a></dd>
			<dd><a href="/bbs/recsroomList.php">자료실</a></dd>
			<dd><a href="/bbs/manualList.php">매뉴얼</a></dd>
			<dd><a href="/bbs/stdOpertProcssList.php">표준작업절차</a></dd>
			<dd><a href="/bbs/dsstrCaseList.php">재해사례</a></dd>
			<dd><a href="sub00706.php">안전용품업체</a></dd>
			<dd><a href="/bbs/vocList.php">VOC</a></dd>
		</dl>
		 <dl>
			<dd><a href="/system/userMngList.php">사용자관리</a></dd>
			<dd><a href="/system/connectLogList.php">접속로그</a></dd>
			<dd><a href="sub00803.php">시스템 사용관리</a></dd>
			<dd><a href="/system/codeMngList.php">코드관리</a></dd>
			<dd><a href="/system/authMngList.php">권한관리</a></dd>
			<dd><a href="/system/popupMngList.php">팝업관리</a></dd>
			<dd><a href="/system/accessAuth.php">접근권한</a></dd>
			<dd><a href="/system/categoryList.php">카테고리관리</a></dd>
		 </dl>
			
<!-- 			<dd><a href="sub00401.php">월간활동 관리계획</a></dd> -->
<!-- 			<dd><a href="sub071.php">현장관리</a></dd> -->
<!-- 			<dd><a href="sub075.php">비상연락망</a></dd> -->
<!-- 			<dd><a href="sub031.php">교육관리</a></dd> -->
<!-- 			<dd><a href="sub055.php">안전보건관리규정</a></dd> -->
<!-- 			<dd><a href="sub052.php">지정서</a></dd> -->
<!-- 			<dd><a href="sub0210.php">중량물 취급 계획</a></dd> -->
<!-- 			<dd><a href="sub0211.php">안전용품</a></dd> -->
<!-- 			<dd><a href="sub048.php">비상조치계획</a></dd> -->
<!-- 			<dd><a href="sub049.php">산업안전보건관리비</a></dd> -->
<!-- 			<dd><a href="sub0411.php">안전관리대관서류</a></dd> -->
		</section>
	</nav>